name: Terraform Destroy

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  terraform_destroy:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0  # Replace with your desired Terraform version

    - name: Terraform Init
      run: |
        terraform init

    - name: Terraform Destroy
      run: |
        terraform destroy -auto-approve

